# Generated by Django 6.0.2 on 2026-02-18 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Nombre de usuario')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Está activo?')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(default='profile_pics/default_profile.png', upload_to='profile_pics/', verbose_name='Foto de perfil')),
                ('biografia', models.TextField(max_length=500, verbose_name='Biografia')),
                ('visibilidad', models.BooleanField(default=True, verbose_name='Visibilidad')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
                'db_table': 'profile',
            },
        ),
        migrations.CreateModel(
            name='InfoPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('telefono', models.CharField(max_length=11, verbose_name='Telefono')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('altura_cm', models.FloatField(blank=True, null=True, verbose_name='Altura en cm')),
                ('peso_kg', models.FloatField(blank=True, null=True, verbose_name='Peso en kg')),
                ('fecha_union', models.DateTimeField(auto_now=True, verbose_name='Fecha de union')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info_personal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dato',
                'verbose_name_plural': 'Datos',
                'db_table': 'information_personal',
                'ordering': ['id', 'fecha_union'],
            },
        ),
    ]
