# Generated by Django 6.0.2 on 2026-02-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='biografia',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Biografia'),
        ),
    ]
