# Generated by Django 6.0.2 on 2026-05-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_usuario_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infopersonal',
            name='fecha_union',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de union'),
        ),
    ]
