# Generated by Django 6.0.2 on 2026-05-02 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('duracion', models.IntegerField(blank=True, null=True, verbose_name='Duración en segundos')),
                ('descripcion', models.TextField(blank=True, max_length=500, null=True, verbose_name='Descripción')),
                ('repeticiones', models.IntegerField(blank=True, null=True, verbose_name='Repeticiones')),
            ],
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, max_length=500, null=True, verbose_name='Descripcion de la rutina')),
                ('duracion_total', models.IntegerField(blank=True, null=True, verbose_name='Duracion total')),
                ('ejercicios', models.ManyToManyField(blank=True, related_name='ejercicios', to='Workout.exercise', verbose_name='Ejercicios')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
