# Generated by Django 6.0.2 on 2026-05-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='dificultad',
            field=models.CharField(choices=[('begginer', 'Principiante'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado')], default='begginer', max_length=20, verbose_name='Dificultad'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='location',
            field=models.CharField(choices=[('home', 'Casa'), ('gym', 'Gimnasio'), ('outdoor', 'Exterior')], default='home', max_length=20, verbose_name='Entorno'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='miniatura',
            field=models.ImageField(blank=True, null=True, upload_to='exercise_thumbnails/', verbose_name='Miniatura'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='patron_movimiento',
            field=models.CharField(choices=[('push', 'Empuje'), ('pull', 'Tirón'), ('squat', 'Sentadilla'), ('hinge', 'Cadera'), ('carry', 'Carga')], default='pull', max_length=20, verbose_name='Patron de movimiento'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='video',
            field=models.URLField(blank=True, null=True, verbose_name='Video'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='muscle_group',
            field=models.ManyToManyField(related_name='exercises', to='Workout.musclegroup', verbose_name='Grupo muscular'),
        ),
    ]
