# Generated by Django 6.0.2 on 2026-05-07 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workout', '0002_musclegroup_exercise_dificultad_exercise_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='duracion',
            field=models.IntegerField(blank=True, null=True, verbose_name='Duración por repetición'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='repeticiones',
            field=models.IntegerField(blank=True, null=True, verbose_name='Repeticiones por ronda'),
        ),
    ]
