# Generated by Django 6.0.2 on 2026-05-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workout', '0003_alter_exercise_duracion_alter_exercise_repeticiones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='miniatura',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Miniatura'),
        ),
    ]
