# Generated by Django 6.0.2 on 2026-05-08 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workout', '0004_alter_exercise_miniatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='location',
            field=models.CharField(choices=[('Casa', 'Casa'), ('Gimnasio', 'Gimnasio'), ('Exterior', 'Exterior')], default='Casa', max_length=20, verbose_name='Entorno'),
        ),
    ]
