# Generated by Django 6.0.2 on 2026-05-08 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workout', '0005_alter_exercise_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='dificultad',
            field=models.CharField(choices=[('Principiante', 'Principiante'), ('Intermedio', 'Intermedio'), ('Avanzado', 'Avanzado')], default='Principiante', max_length=20, verbose_name='Dificultad'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='patron_movimiento',
            field=models.CharField(choices=[('Empuje', 'Empuje'), ('Tirón', 'Tirón'), ('Sentadilla', 'Sentadilla'), ('Cadera', 'Cadera'), ('Carga', 'Carga')], default='Tirón', max_length=20, verbose_name='Patron de movimiento'),
        ),
    ]
