# Generated by Django 6.0.2 on 2026-05-08 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workout', '0006_alter_exercise_dificultad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='dificultad',
            field=models.CharField(choices=[('begginer', 'Principiante'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado')], default='begginer', max_length=20, verbose_name='Dificultad'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='location',
            field=models.CharField(choices=[('home', 'Casa'), ('gym', 'Gimnasio'), ('outdoor', 'Exterior')], default='home', max_length=20, verbose_name='Entorno'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='patron_movimiento',
            field=models.CharField(choices=[('push', 'Empuje'), ('pull', 'Tirón'), ('squat', 'Sentadilla'), ('hinge', 'Cadera'), ('carry', 'Carga')], default='pull', max_length=20, verbose_name='Patron de movimiento'),
        ),
    ]
