# Generated by Django 6.0.2 on 2026-05-09 10:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workout', '0007_alter_exercise_dificultad_alter_exercise_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routine',
            name='duracion_total',
        ),
        migrations.AddField(
            model_name='routine',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='routine',
            name='visibilidad',
            field=models.BooleanField(default=False, verbose_name='Visibilidad'),
        ),
        migrations.AlterField(
            model_name='routine',
            name='ejercicios',
            field=models.ManyToManyField(blank=True, related_name='rutinas', to='Workout.exercise', verbose_name='Ejercicios'),
        ),
        migrations.AlterField(
            model_name='routine',
            name='nombre',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Nombre'),
            preserve_default=False,
        ),
    ]
