# Generated by Django 6.0.2 on 2026-05-11 16:27

import Social.models.content_model
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='content',
            name='tipo_archivo',
            field=models.CharField(choices=[('image', 'Imagen'), ('video', 'Video')], default='image'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='contenido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Social.content', verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='content',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to=Social.models.content_model.user_content_path, verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='content',
            name='fecha_publicacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='favourite',
            name='contenido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to='Social.content', verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='like',
            name='contenido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='Social.content', verbose_name='Contenido'),
        ),
    ]
