# Generated by Django 6.0.2 on 2026-05-13 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0003_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='publicacion',
            new_name='contenido',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='usuario',
            new_name='destinatario',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='leido',
            new_name='leida',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='mensaje',
        ),
        migrations.AddField(
            model_name='notification',
            name='emisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
