# Generated by Django 6.0.2 on 2026-05-14 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0004_rename_publicacion_notification_contenido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='tipo_archivo',
            field=models.CharField(choices=[('image', 'Imagen'), ('video', 'Video')], default='image', max_length=50),
        ),
    ]
